# Building Predictive Models

In [1]:
import pandas as pd
import os
import numpy as np


### import the pre-processed data


In [2]:
processed_data_path = os.path.join(os.path.pardir, 'data','processed')
train_file_path = os.path.join(processed_data_path, 'train.csv')
test_file_path = os.path.join(processed_data_path, 'test.csv')

In [3]:
train_df = pd.read_csv(train_file_path, index_col='PassengerId')
test_df = pd.read_csv(test_file_path, index_col='PassengerId')

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
Survived              891 non-null int64
Age                   891 non-null float64
Fare                  891 non-null float64
FamilySize            891 non-null int64
IsMother              891 non-null int64
IsMale                891 non-null int64
Deck_A                891 non-null int64
Deck_B                891 non-null int64
Deck_C                891 non-null int64
Deck_D                891 non-null int64
Deck_E                891 non-null int64
Deck_F                891 non-null int64
Deck_G                891 non-null int64
Deck_Z                891 non-null int64
Pclass_1              891 non-null int64
Pclass_2              891 non-null int64
Pclass_3              891 non-null int64
Title_Lady            891 non-null int64
Title_Master          891 non-null int64
Title_Miss            891 non-null int64
Title_Mr              891 non-null int64
Title_Mrs             891 non-

In [5]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 32 columns):
Age                   418 non-null float64
Fare                  418 non-null float64
FamilySize            418 non-null int64
IsMother              418 non-null int64
IsMale                418 non-null int64
Deck_A                418 non-null int64
Deck_B                418 non-null int64
Deck_C                418 non-null int64
Deck_D                418 non-null int64
Deck_E                418 non-null int64
Deck_F                418 non-null int64
Deck_G                418 non-null int64
Deck_Z                418 non-null int64
Pclass_1              418 non-null int64
Pclass_2              418 non-null int64
Pclass_3              418 non-null int64
Title_Lady            418 non-null int64
Title_Master          418 non-null int64
Title_Miss            418 non-null int64
Title_Mr              418 non-null int64
Title_Mrs             418 non-null int64
Title_Officer         418 n

### Data Preparation

In [6]:
# most machine learning algorithms expect numerical arrays, so let's set those up
# Please note we are ONLY working on the training data frame here.  
X = train_df.loc[:,'Age':].as_matrix().astype('float') #all rows and columns, except SURVIVED
y = train_df['Survived'].ravel() #ravel creates a flat 1-d array

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [7]:
print X.shape, y.shape

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(X.shape, y.shape)? (<ipython-input-7-90a94319c11e>, line 1)

In [ ]:
print(X.shape, y.shape)

In [ ]:
# X this means 891 rows, and 32 colums/features, not including survived
# y this means 891 one dimensional array, one feature, just containing 0 or 1 for Survived


In [9]:
#Now split the training data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(712, 32) (712,)
(179, 32) (179,)


In [10]:
#We've just split the data into 80/20 
# Now let's see how many positive class values are in the train and test data
# Mean will give us the proportion of positives (i.e. 1 = SURVIVED)
print('Mean survival in the 80% training data: {0:.3f}'.format(np.mean(y_train)))
print('Mean survival in the 20% training test data: {0:.3f}'.format(np.mean(y_test)))

Mean survival in the 80% training data: 0.383
Mean survival in the 20% training test data: 0.385


In [11]:
# We have similar proportions in the 80% and 20% splits.  This is good - this is what we want, 
# an even distribution
#
# Only 39% of data has positive cases, so 61% are going to be negative.  That's a little biased
# in terms of our source data.  This is known as class imbalance.

## check scikit-learn version

In [13]:
import sklearn
sklearn.__version__
# we need at least 0.19 onwards

'0.19.1'

## Create baseline model

In [14]:
# We want to know what our data precision and accuracy looks like BEFORE we start to do machine learning
from sklearn.dummy import DummyClassifier
# The dummy classifier gives you a measure of "baseline" performance--i.e. the success rate one should expect to achieve even if simply guessing.
# https://stackoverflow.com/questions/29441943/what-is-the-theorical-foundation-for-scikit-learn-dummy-classifier
#


In [15]:
#create a model
# most_frequent we want the model to output the majority class - i.e. 0/Not Survived in our case
model_dummy = DummyClassifier(strategy='most_frequent', random_state=0)
#
# Train the model using fit() with the input data, and the output data.  
model_dummy.fit(X_train, y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [16]:
# let's evaluate the performance.
# The model will predict the output against X_test and then it will compare it against the actual y_test
# The classification model will represent the model accuracy
print('Score for baseline mode : {0:.2f}'.format(model_dummy.score(X_test, y_test)))

Score for baseline mode : 0.61


In [17]:
# 61% baseline accuracy.  Without any algorithms, if you always predict 0/Not Survived, you will have a 61% success rate

### other performance metrics

In [24]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score
# Method signatures are Actual Output, Predicited Output.  We can use the predict function on the input data to easily get the prediciton
print('Accuracy for baseline model: {0:.2f}'.format(accuracy_score(y_test, model_dummy.predict(X_test))))
print('Confusion Matrix for baseline model: \n {0}'.format(confusion_matrix(y_test, model_dummy.predict(X_test))))
# Our confusion matrix shows that we are always predicting 0 (Negative class)

Accuracy for baseline model: 0.61
Confusion Matrix for baseline model: 
 [[110   0]
 [ 69   0]]


In [25]:
print('Precision for baseline model: {0:.2f}'.format(precision_score(y_test, model_dummy.predict(X_test))))
print('Recall for baseline model: {0:.2f}'.format(recall_score(y_test, model_dummy.predict(X_test))))

Precision for baseline model: 0.00
Recall for baseline model: 0.00


/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


## Submit to Kaggle


In [46]:
#convert the test data frame to a 2d matrix in float type
# test_df is the data frame for which we do not have the answers - Kaggle has the answers!
# we submit our prediction output, and Kaggle compares with actual output.
test_X = test_df.as_matrix().astype('float')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  after removing the cwd from sys.path.


In [31]:
# Get predicitions from the data
predictions = model_dummy.predict(test_X)
# All our predictions will be 0/Not Survived - which should have a 61% success rate, right?

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]


In [35]:
# Combine our predicitions with their passengerIds
# The file to submit to Kaggle is in format PassengerId : Survived 
# Build it in a pandas data frame from the index value of the test_df dataframe
df_submission = pd.DataFrame({'PassengerId': test_df.index,'Survived': predictions})

In [36]:
#Let's look at the content of the data frame
df_submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [44]:
#save this data frame down to disk
submission_data_path = os.path.join(os.path.pardir, 'data','external')
submission_file_path = os.path.join(submission_data_path, '01_dummy.csv')

In [45]:
df_submission.to_csv(submission_file_path, index=False) #index=False so there's no extra index column in the file

In [47]:
# We want to create a function to do all this, since we'll be doing this again and again for subseqnet submissions
def get_submission_file(model, filename):
    #convert to matrix
    test_X = test_df.as_matrix().astype('float')
    #make prediciton
    predictions = model.predict(test_X)
    #create submission data frame
    df_submission = pd.DataFrame({'PassengerId': test_df.index,'Survived': predictions})
    #create submission file object
    submission_data_path = os.path.join(os.path.pardir, 'data','external')
    submission_file_path = os.path.join(submission_data_path, filename)
    #write to disk
    df_submission.to_csv(submission_file_path, index=False)

In [ ]:
# get the submission file - we have to manully submitt this file.
get_submission_file(model_dummy, '01_dummy.csv')

## Logistic Regression Modelling

In [51]:
# import the function from scikit-learn
from sklearn.linear_model import LogisticRegression
# create the model
model_lr_1 = LogisticRegression(random_state=0)
# train the model
model_lr_1.fit(X_train, y_train)
# evaluate the model
print('Score for logistic regression v0.1: {0:.2f}'.format(model_lr_1.score(X_test, y_test)))

Score for logistic regression v0.1: 0.83


In [52]:
# The model preformance improved from 0.61 to 0.83  
# Our predictive model is therefore better than our baseline


### Performance metrics for the model

In [54]:
# Method signatures are Actual Output, Predicited Output.  We can use the predict function on the input data to easily get the prediciton
print('Accuracy for logistic regression v0.1 model: {0:.2f}'.format(accuracy_score(y_test, model_lr_1.predict(X_test))))
print('Confusion Matrix for logistic regression v0.1  model: \n {0}'.format(confusion_matrix(y_test, model_lr_1.predict(X_test))))
# Our confusion matrix shows that we are always predicting 0 (Negative class)
print('Precision for logistic regression v0.1  model: {0:.2f}'.format(precision_score(y_test, model_lr_1.predict(X_test))))
print('Recall for basellogistic regression v0.1 ine model: {0:.2f}'.format(recall_score(y_test, model_lr_1.predict(X_test))))

Accuracy for logistic regression v0.1 model: 0.83
Confusion Matrix for logistic regression v0.1  model: 
 [[95 15]
 [15 54]]
Precision for logistic regression v0.1  model: 0.78
Recall for basellogistic regression v0.1 ine model: 0.78


In [55]:
# Again, the metrics have also improved (precision and recall were both 0 in baseline)
# The point of training a logistical regression model is to find the optimal weights/coefficients b0 and b1
# How to get the coefficients?
model_lr_1.coef_

array([[-0.02842272,  0.00455452, -0.50009091,  0.61781316, -0.8139233 ,
         0.12845079, -0.17281789, -0.39317833,  0.52159977,  1.09941224,
         0.40341217, -0.18345051, -0.30036042,  0.96533486,  0.48256743,
        -0.34483447,  0.28089593,  1.21761327,  0.56363966, -1.44586304,
         1.07245552, -0.11273706, -0.47293647,  0.16255646,  0.24716929,
         0.28009437,  0.4132477 ,  0.49183529,  0.46198829,  0.14924424,
         0.37283517,  0.73023265]])

In [56]:
# These are the coefficients for each of the different input features.
# These coefficients are also known as model weights or Parameters.  So in the process of training a model, these 
# parameters are internally optimised during the training process.  This is how training works.
#
# If we wanted to know about the relative impact of input features on the outputs, then we can leverage these coefficients
# to get some useful inferences...  TBD.

## Second Kaggle Submission

In [57]:
#build file
get_submission_file(model_lr_1, '02_lr.csv')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  after removing the cwd from sys.path.


In [58]:
# our ranking improved :D